# Generated by Django 4.2.4 on 2023-09-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time_table',
            old_name='roll_no',
            new_name='student',
        ),
    ]
