# Generated by Django 4.2.4 on 2023-09-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_roll_no_time_table_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_table',
            name='exit_time',
            field=models.DateTimeField(null=True),
        ),
    ]
